// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace field
{

public enum ActorState : sbyte
{
  Idle = 0,
  Move = 1,
  Attack = 2,
  Cast = 3,
  Dead = 4,
};


}
