// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace field
{

public enum AiStateType : sbyte
{
  Idle = 0,
  Patrol = 1,
  Chase = 2,
  Attack = 3,
  Return = 4,
  Dead = 5,
};


}
