// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace field
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct AiStateEvent : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_25_9_23(); }
  public static AiStateEvent GetRootAsAiStateEvent(ByteBuffer _bb) { return GetRootAsAiStateEvent(_bb, new AiStateEvent()); }
  public static AiStateEvent GetRootAsAiStateEvent(ByteBuffer _bb, AiStateEvent obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public AiStateEvent __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public field.EntityType EntityType { get { int o = __p.__offset(4); return o != 0 ? (field.EntityType)__p.bb.GetSbyte(o + __p.bb_pos) : field.EntityType.Monster; } }
  public ulong EntityId { get { int o = __p.__offset(6); return o != 0 ? __p.bb.GetUlong(o + __p.bb_pos) : (ulong)0; } }
  public field.AiStateType State { get { int o = __p.__offset(8); return o != 0 ? (field.AiStateType)__p.bb.GetSbyte(o + __p.bb_pos) : field.AiStateType.Idle; } }

  public static Offset<field.AiStateEvent> CreateAiStateEvent(FlatBufferBuilder builder,
      field.EntityType entityType = field.EntityType.Monster,
      ulong entityId = 0,
      field.AiStateType state = field.AiStateType.Idle) {
    builder.StartTable(3);
    AiStateEvent.AddEntityId(builder, entityId);
    AiStateEvent.AddState(builder, state);
    AiStateEvent.AddEntityType(builder, entityType);
    return AiStateEvent.EndAiStateEvent(builder);
  }

  public static void StartAiStateEvent(FlatBufferBuilder builder) { builder.StartTable(3); }
  public static void AddEntityType(FlatBufferBuilder builder, field.EntityType entityType) { builder.AddSbyte(0, (sbyte)entityType, 1); }
  public static void AddEntityId(FlatBufferBuilder builder, ulong entityId) { builder.AddUlong(1, entityId, 0); }
  public static void AddState(FlatBufferBuilder builder, field.AiStateType state) { builder.AddSbyte(2, (sbyte)state, 0); }
  public static Offset<field.AiStateEvent> EndAiStateEvent(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<field.AiStateEvent>(o);
  }
}


static public class AiStateEventVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyField(tablePos, 4 /*EntityType*/, 1 /*field.EntityType*/, 1, false)
      && verifier.VerifyField(tablePos, 6 /*EntityId*/, 8 /*ulong*/, 8, false)
      && verifier.VerifyField(tablePos, 8 /*State*/, 1 /*field.AiStateType*/, 1, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}

}
