// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace field
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct CombatEvent : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_25_9_23(); }
  public static CombatEvent GetRootAsCombatEvent(ByteBuffer _bb) { return GetRootAsCombatEvent(_bb, new CombatEvent()); }
  public static CombatEvent GetRootAsCombatEvent(ByteBuffer _bb, CombatEvent obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public CombatEvent __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public field.EntityType AttackerType { get { int o = __p.__offset(4); return o != 0 ? (field.EntityType)__p.bb.GetSbyte(o + __p.bb_pos) : field.EntityType.Player; } }
  public ulong AttackerId { get { int o = __p.__offset(6); return o != 0 ? __p.bb.GetUlong(o + __p.bb_pos) : (ulong)0; } }
  public field.EntityType TargetType { get { int o = __p.__offset(8); return o != 0 ? (field.EntityType)__p.bb.GetSbyte(o + __p.bb_pos) : field.EntityType.Player; } }
  public ulong TargetId { get { int o = __p.__offset(10); return o != 0 ? __p.bb.GetUlong(o + __p.bb_pos) : (ulong)0; } }
  public int Damage { get { int o = __p.__offset(12); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public int RemainHp { get { int o = __p.__offset(14); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }

  public static Offset<field.CombatEvent> CreateCombatEvent(FlatBufferBuilder builder,
      field.EntityType attackerType = field.EntityType.Player,
      ulong attackerId = 0,
      field.EntityType targetType = field.EntityType.Player,
      ulong targetId = 0,
      int damage = 0,
      int remainHp = 0) {
    builder.StartTable(6);
    CombatEvent.AddTargetId(builder, targetId);
    CombatEvent.AddAttackerId(builder, attackerId);
    CombatEvent.AddRemainHp(builder, remainHp);
    CombatEvent.AddDamage(builder, damage);
    CombatEvent.AddTargetType(builder, targetType);
    CombatEvent.AddAttackerType(builder, attackerType);
    return CombatEvent.EndCombatEvent(builder);
  }

  public static void StartCombatEvent(FlatBufferBuilder builder) { builder.StartTable(6); }
  public static void AddAttackerType(FlatBufferBuilder builder, field.EntityType attackerType) { builder.AddSbyte(0, (sbyte)attackerType, 0); }
  public static void AddAttackerId(FlatBufferBuilder builder, ulong attackerId) { builder.AddUlong(1, attackerId, 0); }
  public static void AddTargetType(FlatBufferBuilder builder, field.EntityType targetType) { builder.AddSbyte(2, (sbyte)targetType, 0); }
  public static void AddTargetId(FlatBufferBuilder builder, ulong targetId) { builder.AddUlong(3, targetId, 0); }
  public static void AddDamage(FlatBufferBuilder builder, int damage) { builder.AddInt(4, damage, 0); }
  public static void AddRemainHp(FlatBufferBuilder builder, int remainHp) { builder.AddInt(5, remainHp, 0); }
  public static Offset<field.CombatEvent> EndCombatEvent(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<field.CombatEvent>(o);
  }
}


static public class CombatEventVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyField(tablePos, 4 /*AttackerType*/, 1 /*field.EntityType*/, 1, false)
      && verifier.VerifyField(tablePos, 6 /*AttackerId*/, 8 /*ulong*/, 8, false)
      && verifier.VerifyField(tablePos, 8 /*TargetType*/, 1 /*field.EntityType*/, 1, false)
      && verifier.VerifyField(tablePos, 10 /*TargetId*/, 8 /*ulong*/, 8, false)
      && verifier.VerifyField(tablePos, 12 /*Damage*/, 4 /*int*/, 4, false)
      && verifier.VerifyField(tablePos, 14 /*RemainHp*/, 4 /*int*/, 4, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}

}
