// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace field
{

public enum EntityType : sbyte
{
  Player = 0,
  Monster = 1,
  Npc = 2,
};


}
