// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace field
{

public enum FieldCmdType : sbyte
{
  Enter = 0,
  Leave = 1,
  Move = 2,
};


}
