// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace field
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct FieldCmd : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_25_9_23(); }
  public static FieldCmd GetRootAsFieldCmd(ByteBuffer _bb) { return GetRootAsFieldCmd(_bb, new FieldCmd()); }
  public static FieldCmd GetRootAsFieldCmd(ByteBuffer _bb, FieldCmd obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public FieldCmd __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public field.FieldCmdType Type { get { int o = __p.__offset(4); return o != 0 ? (field.FieldCmdType)__p.bb.GetSbyte(o + __p.bb_pos) : field.FieldCmdType.Enter; } }
  public field.EntityType EntityType { get { int o = __p.__offset(6); return o != 0 ? (field.EntityType)__p.bb.GetSbyte(o + __p.bb_pos) : field.EntityType.Player; } }
  public ulong EntityId { get { int o = __p.__offset(8); return o != 0 ? __p.bb.GetUlong(o + __p.bb_pos) : (ulong)0; } }
  public field.Vec2? Pos { get { int o = __p.__offset(10); return o != 0 ? (field.Vec2?)(new field.Vec2()).__assign(__p.__indirect(o + __p.bb_pos), __p.bb) : null; } }
  public field.Vec2? Dir { get { int o = __p.__offset(12); return o != 0 ? (field.Vec2?)(new field.Vec2()).__assign(__p.__indirect(o + __p.bb_pos), __p.bb) : null; } }
  public string Prefab { get { int o = __p.__offset(14); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetPrefabBytes() { return __p.__vector_as_span<byte>(14, 1); }
#else
  public ArraySegment<byte>? GetPrefabBytes() { return __p.__vector_as_arraysegment(14); }
#endif
  public byte[] GetPrefabArray() { return __p.__vector_as_array<byte>(14); }

  public static Offset<field.FieldCmd> CreateFieldCmd(FlatBufferBuilder builder,
      field.FieldCmdType type = field.FieldCmdType.Enter,
      field.EntityType entityType = field.EntityType.Player,
      ulong entityId = 0,
      Offset<field.Vec2> posOffset = default(Offset<field.Vec2>),
      Offset<field.Vec2> dirOffset = default(Offset<field.Vec2>),
      StringOffset prefabOffset = default(StringOffset)) {
    builder.StartTable(6);
    FieldCmd.AddEntityId(builder, entityId);
    FieldCmd.AddPrefab(builder, prefabOffset);
    FieldCmd.AddDir(builder, dirOffset);
    FieldCmd.AddPos(builder, posOffset);
    FieldCmd.AddEntityType(builder, entityType);
    FieldCmd.AddType(builder, type);
    return FieldCmd.EndFieldCmd(builder);
  }

  public static void StartFieldCmd(FlatBufferBuilder builder) { builder.StartTable(6); }
  public static void AddType(FlatBufferBuilder builder, field.FieldCmdType type) { builder.AddSbyte(0, (sbyte)type, 0); }
  public static void AddEntityType(FlatBufferBuilder builder, field.EntityType entityType) { builder.AddSbyte(1, (sbyte)entityType, 0); }
  public static void AddEntityId(FlatBufferBuilder builder, ulong entityId) { builder.AddUlong(2, entityId, 0); }
  public static void AddPos(FlatBufferBuilder builder, Offset<field.Vec2> posOffset) { builder.AddOffset(3, posOffset.Value, 0); }
  public static void AddDir(FlatBufferBuilder builder, Offset<field.Vec2> dirOffset) { builder.AddOffset(4, dirOffset.Value, 0); }
  public static void AddPrefab(FlatBufferBuilder builder, StringOffset prefabOffset) { builder.AddOffset(5, prefabOffset.Value, 0); }
  public static Offset<field.FieldCmd> EndFieldCmd(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<field.FieldCmd>(o);
  }
}


static public class FieldCmdVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyField(tablePos, 4 /*Type*/, 1 /*field.FieldCmdType*/, 1, false)
      && verifier.VerifyField(tablePos, 6 /*EntityType*/, 1 /*field.EntityType*/, 1, false)
      && verifier.VerifyField(tablePos, 8 /*EntityId*/, 8 /*ulong*/, 8, false)
      && verifier.VerifyTable(tablePos, 10 /*Pos*/, field.Vec2Verify.Verify, false)
      && verifier.VerifyTable(tablePos, 12 /*Dir*/, field.Vec2Verify.Verify, false)
      && verifier.VerifyString(tablePos, 14 /*Prefab*/, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}

}
