// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace field
{

public enum Packet : byte
{
  NONE = 0,
  FieldCmd = 1,
  CombatEvent = 2,
  AiStateEvent = 3,
  StatEvent = 4,
};



static public class PacketVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, byte typeId, uint tablePos)
  {
    bool result = true;
    switch((Packet)typeId)
    {
      case Packet.FieldCmd:
        result = field.FieldCmdVerify.Verify(verifier, tablePos);
        break;
      case Packet.CombatEvent:
        result = field.CombatEventVerify.Verify(verifier, tablePos);
        break;
      case Packet.AiStateEvent:
        result = field.AiStateEventVerify.Verify(verifier, tablePos);
        break;
      case Packet.StatEvent:
        result = field.StatEventVerify.Verify(verifier, tablePos);
        break;
      default: result = true;
        break;
    }
    return result;
  }
}


}
