// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace field
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct StatEvent : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_25_9_23(); }
  public static StatEvent GetRootAsStatEvent(ByteBuffer _bb) { return GetRootAsStatEvent(_bb, new StatEvent()); }
  public static StatEvent GetRootAsStatEvent(ByteBuffer _bb, StatEvent obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public StatEvent __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public field.EntityType EntityType { get { int o = __p.__offset(4); return o != 0 ? (field.EntityType)__p.bb.GetSbyte(o + __p.bb_pos) : field.EntityType.Player; } }
  public ulong EntityId { get { int o = __p.__offset(6); return o != 0 ? __p.bb.GetUlong(o + __p.bb_pos) : (ulong)0; } }
  public int Hp { get { int o = __p.__offset(8); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public int MaxHp { get { int o = __p.__offset(10); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public int Sp { get { int o = __p.__offset(12); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public int MaxSp { get { int o = __p.__offset(14); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }

  public static Offset<field.StatEvent> CreateStatEvent(FlatBufferBuilder builder,
      field.EntityType entityType = field.EntityType.Player,
      ulong entityId = 0,
      int hp = 0,
      int maxHp = 0,
      int sp = 0,
      int maxSp = 0) {
    builder.StartTable(6);
    StatEvent.AddEntityId(builder, entityId);
    StatEvent.AddMaxSp(builder, maxSp);
    StatEvent.AddSp(builder, sp);
    StatEvent.AddMaxHp(builder, maxHp);
    StatEvent.AddHp(builder, hp);
    StatEvent.AddEntityType(builder, entityType);
    return StatEvent.EndStatEvent(builder);
  }

  public static void StartStatEvent(FlatBufferBuilder builder) { builder.StartTable(6); }
  public static void AddEntityType(FlatBufferBuilder builder, field.EntityType entityType) { builder.AddSbyte(0, (sbyte)entityType, 0); }
  public static void AddEntityId(FlatBufferBuilder builder, ulong entityId) { builder.AddUlong(1, entityId, 0); }
  public static void AddHp(FlatBufferBuilder builder, int hp) { builder.AddInt(2, hp, 0); }
  public static void AddMaxHp(FlatBufferBuilder builder, int maxHp) { builder.AddInt(3, maxHp, 0); }
  public static void AddSp(FlatBufferBuilder builder, int sp) { builder.AddInt(4, sp, 0); }
  public static void AddMaxSp(FlatBufferBuilder builder, int maxSp) { builder.AddInt(5, maxSp, 0); }
  public static Offset<field.StatEvent> EndStatEvent(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<field.StatEvent>(o);
  }
}


static public class StatEventVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyField(tablePos, 4 /*EntityType*/, 1 /*field.EntityType*/, 1, false)
      && verifier.VerifyField(tablePos, 6 /*EntityId*/, 8 /*ulong*/, 8, false)
      && verifier.VerifyField(tablePos, 8 /*Hp*/, 4 /*int*/, 4, false)
      && verifier.VerifyField(tablePos, 10 /*MaxHp*/, 4 /*int*/, 4, false)
      && verifier.VerifyField(tablePos, 12 /*Sp*/, 4 /*int*/, 4, false)
      && verifier.VerifyField(tablePos, 14 /*MaxSp*/, 4 /*int*/, 4, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}

}
