// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace game
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct EnterFieldAck : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_25_9_23(); }
  public static EnterFieldAck GetRootAsEnterFieldAck(ByteBuffer _bb) { return GetRootAsEnterFieldAck(_bb, new EnterFieldAck()); }
  public static EnterFieldAck GetRootAsEnterFieldAck(ByteBuffer _bb, EnterFieldAck obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public EnterFieldAck __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public uint FieldId { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetUint(o + __p.bb_pos) : (uint)0; } }
  public ulong PlayerId { get { int o = __p.__offset(6); return o != 0 ? __p.bb.GetUlong(o + __p.bb_pos) : (ulong)0; } }

  public static Offset<game.EnterFieldAck> CreateEnterFieldAck(FlatBufferBuilder builder,
      uint field_id = 0,
      ulong player_id = 0) {
    builder.StartTable(2);
    EnterFieldAck.AddPlayerId(builder, player_id);
    EnterFieldAck.AddFieldId(builder, field_id);
    return EnterFieldAck.EndEnterFieldAck(builder);
  }

  public static void StartEnterFieldAck(FlatBufferBuilder builder) { builder.StartTable(2); }
  public static void AddFieldId(FlatBufferBuilder builder, uint fieldId) { builder.AddUint(0, fieldId, 0); }
  public static void AddPlayerId(FlatBufferBuilder builder, ulong playerId) { builder.AddUlong(1, playerId, 0); }
  public static Offset<game.EnterFieldAck> EndEnterFieldAck(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<game.EnterFieldAck>(o);
  }
}


static public class EnterFieldAckVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyField(tablePos, 4 /*FieldId*/, 4 /*uint*/, 4, false)
      && verifier.VerifyField(tablePos, 6 /*PlayerId*/, 8 /*ulong*/, 8, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}

}
