// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace game
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct EnterField : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_25_9_23(); }
  public static EnterField GetRootAsEnterField(ByteBuffer _bb) { return GetRootAsEnterField(_bb, new EnterField()); }
  public static EnterField GetRootAsEnterField(ByteBuffer _bb, EnterField obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public EnterField __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public uint FieldId { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetUint(o + __p.bb_pos) : (uint)0; } }

  public static Offset<game.EnterField> CreateEnterField(FlatBufferBuilder builder,
      uint field_id = 0) {
    builder.StartTable(1);
    EnterField.AddFieldId(builder, field_id);
    return EnterField.EndEnterField(builder);
  }

  public static void StartEnterField(FlatBufferBuilder builder) { builder.StartTable(1); }
  public static void AddFieldId(FlatBufferBuilder builder, uint fieldId) { builder.AddUint(0, fieldId, 0); }
  public static Offset<game.EnterField> EndEnterField(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<game.EnterField>(o);
  }
}


static public class EnterFieldVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyField(tablePos, 4 /*FieldId*/, 4 /*uint*/, 4, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}

}
