// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace game
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct Envelope : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_25_9_23(); }
  public static Envelope GetRootAsEnvelope(ByteBuffer _bb) { return GetRootAsEnvelope(_bb, new Envelope()); }
  public static Envelope GetRootAsEnvelope(ByteBuffer _bb, Envelope obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public static bool VerifyEnvelope(ByteBuffer _bb) {Google.FlatBuffers.Verifier verifier = new Google.FlatBuffers.Verifier(_bb); return verifier.VerifyBuffer("", false, EnvelopeVerify.Verify); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public Envelope __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public game.Packet PktType { get { int o = __p.__offset(4); return o != 0 ? (game.Packet)__p.bb.Get(o + __p.bb_pos) : game.Packet.NONE; } }
  public TTable? Pkt<TTable>() where TTable : struct, IFlatbufferObject { int o = __p.__offset(6); return o != 0 ? (TTable?)__p.__union<TTable>(o + __p.bb_pos) : null; }
  public game.Ping PktAsPing() { return Pkt<game.Ping>().Value; }
  public game.Login PktAsLogin() { return Pkt<game.Login>().Value; }
  public game.EnterField PktAsEnterField() { return Pkt<game.EnterField>().Value; }
  public game.LoginAck PktAsLoginAck() { return Pkt<game.LoginAck>().Value; }
  public game.EnterFieldAck PktAsEnterFieldAck() { return Pkt<game.EnterFieldAck>().Value; }
  public game.SkillCmd PktAsSkillCmd() { return Pkt<game.SkillCmd>().Value; }

  public static Offset<game.Envelope> CreateEnvelope(FlatBufferBuilder builder,
      game.Packet pkt_type = game.Packet.NONE,
      int pktOffset = 0) {
    builder.StartTable(2);
    Envelope.AddPkt(builder, pktOffset);
    Envelope.AddPktType(builder, pkt_type);
    return Envelope.EndEnvelope(builder);
  }

  public static void StartEnvelope(FlatBufferBuilder builder) { builder.StartTable(2); }
  public static void AddPktType(FlatBufferBuilder builder, game.Packet pktType) { builder.AddByte(0, (byte)pktType, 0); }
  public static void AddPkt(FlatBufferBuilder builder, int pktOffset) { builder.AddOffset(1, pktOffset, 0); }
  public static Offset<game.Envelope> EndEnvelope(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<game.Envelope>(o);
  }
  public static void FinishEnvelopeBuffer(FlatBufferBuilder builder, Offset<game.Envelope> offset) { builder.Finish(offset.Value); }
  public static void FinishSizePrefixedEnvelopeBuffer(FlatBufferBuilder builder, Offset<game.Envelope> offset) { builder.FinishSizePrefixed(offset.Value); }
}


static public class EnvelopeVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyField(tablePos, 4 /*PktType*/, 1 /*game.Packet*/, 1, false)
      && verifier.VerifyUnion(tablePos, 4, 6 /*Pkt*/, game.PacketVerify.Verify, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}

}
