// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace game
{

public enum MsgType : byte
{
  NONE = 0,
  Ping = 1,
  Login = 2,
  EnterField = 3,
  LoginAck = 4,
  EnterFieldAck = 5,
  SkillCmd = 6,
  SkillCmdAck = 7,
};


}
