// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace game
{

public enum Packet : byte
{
  NONE = 0,
  Ping = 1,
  Login = 2,
  EnterField = 3,
  LoginAck = 4,
  EnterFieldAck = 5,
  SkillCmd = 6,
  SkillCmdAck = 7,
};



static public class PacketVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, byte typeId, uint tablePos)
  {
    bool result = true;
    switch((Packet)typeId)
    {
      case Packet.Ping:
        result = game.PingVerify.Verify(verifier, tablePos);
        break;
      case Packet.Login:
        result = game.LoginVerify.Verify(verifier, tablePos);
        break;
      case Packet.EnterField:
        result = game.EnterFieldVerify.Verify(verifier, tablePos);
        break;
      case Packet.LoginAck:
        result = game.LoginAckVerify.Verify(verifier, tablePos);
        break;
      case Packet.EnterFieldAck:
        result = game.EnterFieldAckVerify.Verify(verifier, tablePos);
        break;
      case Packet.SkillCmd:
        result = game.SkillCmdVerify.Verify(verifier, tablePos);
        break;
      case Packet.SkillCmdAck:
        result = game.SkillCmdAckVerify.Verify(verifier, tablePos);
        break;
      default: result = true;
        break;
    }
    return result;
  }
}


}
