// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace game
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct SkillCmdAck : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_25_9_23(); }
  public static SkillCmdAck GetRootAsSkillCmdAck(ByteBuffer _bb) { return GetRootAsSkillCmdAck(_bb, new SkillCmdAck()); }
  public static SkillCmdAck GetRootAsSkillCmdAck(ByteBuffer _bb, SkillCmdAck obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public SkillCmdAck __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public game.SkillType Skill { get { int o = __p.__offset(4); return o != 0 ? (game.SkillType)__p.bb.GetSbyte(o + __p.bb_pos) : game.SkillType.NormalAttack; } }
  public ulong TargetId { get { int o = __p.__offset(6); return o != 0 ? __p.bb.GetUlong(o + __p.bb_pos) : (ulong)0; } }
  public bool Ok { get { int o = __p.__offset(8); return o != 0 ? 0!=__p.bb.Get(o + __p.bb_pos) : (bool)true; } }
  public game.SkillError Error { get { int o = __p.__offset(10); return o != 0 ? (game.SkillError)__p.bb.GetSbyte(o + __p.bb_pos) : game.SkillError.None; } }

  public static Offset<game.SkillCmdAck> CreateSkillCmdAck(FlatBufferBuilder builder,
      game.SkillType skill = game.SkillType.NormalAttack,
      ulong targetId = 0,
      bool ok = true,
      game.SkillError error = game.SkillError.None) {
    builder.StartTable(4);
    SkillCmdAck.AddTargetId(builder, targetId);
    SkillCmdAck.AddError(builder, error);
    SkillCmdAck.AddOk(builder, ok);
    SkillCmdAck.AddSkill(builder, skill);
    return SkillCmdAck.EndSkillCmdAck(builder);
  }

  public static void StartSkillCmdAck(FlatBufferBuilder builder) { builder.StartTable(4); }
  public static void AddSkill(FlatBufferBuilder builder, game.SkillType skill) { builder.AddSbyte(0, (sbyte)skill, 0); }
  public static void AddTargetId(FlatBufferBuilder builder, ulong targetId) { builder.AddUlong(1, targetId, 0); }
  public static void AddOk(FlatBufferBuilder builder, bool ok) { builder.AddBool(2, ok, true); }
  public static void AddError(FlatBufferBuilder builder, game.SkillError error) { builder.AddSbyte(3, (sbyte)error, 0); }
  public static Offset<game.SkillCmdAck> EndSkillCmdAck(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<game.SkillCmdAck>(o);
  }
}


static public class SkillCmdAckVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyField(tablePos, 4 /*Skill*/, 1 /*game.SkillType*/, 1, false)
      && verifier.VerifyField(tablePos, 6 /*TargetId*/, 8 /*ulong*/, 8, false)
      && verifier.VerifyField(tablePos, 8 /*Ok*/, 1 /*bool*/, 1, false)
      && verifier.VerifyField(tablePos, 10 /*Error*/, 1 /*game.SkillError*/, 1, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}

}
