// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace game
{

public enum SkillError : sbyte
{
  None = 0,
  OutOfRange = 1,
  Cooldown = 2,
  InvalidTarget = 3,
  InvalidState = 4,
};


}
