// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace game
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct SkillCmd : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_25_9_23(); }
  public static SkillCmd GetRootAsSkillCmd(ByteBuffer _bb) { return GetRootAsSkillCmd(_bb, new SkillCmd()); }
  public static SkillCmd GetRootAsSkillCmd(ByteBuffer _bb, SkillCmd obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public SkillCmd __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public game.SkillType Skill { get { int o = __p.__offset(4); return o != 0 ? (game.SkillType)__p.bb.GetSbyte(o + __p.bb_pos) : game.SkillType.NormalAttack; } }
  public ulong TargetId { get { int o = __p.__offset(6); return o != 0 ? __p.bb.GetUlong(o + __p.bb_pos) : (ulong)0; } }

  public static Offset<game.SkillCmd> CreateSkillCmd(FlatBufferBuilder builder,
      game.SkillType skill = game.SkillType.NormalAttack,
      ulong targetId = 0) {
    builder.StartTable(2);
    SkillCmd.AddTargetId(builder, targetId);
    SkillCmd.AddSkill(builder, skill);
    return SkillCmd.EndSkillCmd(builder);
  }

  public static void StartSkillCmd(FlatBufferBuilder builder) { builder.StartTable(2); }
  public static void AddSkill(FlatBufferBuilder builder, game.SkillType skill) { builder.AddSbyte(0, (sbyte)skill, 0); }
  public static void AddTargetId(FlatBufferBuilder builder, ulong targetId) { builder.AddUlong(1, targetId, 0); }
  public static Offset<game.SkillCmd> EndSkillCmd(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<game.SkillCmd>(o);
  }
}


static public class SkillCmdVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyField(tablePos, 4 /*Skill*/, 1 /*game.SkillType*/, 1, false)
      && verifier.VerifyField(tablePos, 6 /*TargetId*/, 8 /*ulong*/, 8, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}

}
